sudo: false
language: python
matrix:
  include:
  - os: linux
    python: 2.6
  - os: linux
    python: 2.7
  - os: linux
    python: 3.4
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
  - os: linux
    dist: xenial
    python: 3.7
  - os: linux
    python: pypy
  - os: osx
    language: generic
install:
  - scripts/travis.sh pip install --constraint=constraints.txt --requirement=requirements-travis.txt
  - scripts/travis.sh LC_ALL=C pip install .
script:
  - scripts/travis.sh make check
  - scripts/travis.sh make test
after_success:
  - scripts/travis.sh coveralls
branches:
  except:
    - /^[0-9]/
